[source]
git = "https://gitlab.redox-os.org/redox-os/uutils.git"
branch = "redox-unix"

[build]
template = "custom"
script = """
COOKBOOK_CARGO_FLAGS+=(
    --no-default-features
    --features redox
    --bin uutils
)
cookbook_cargo

BINS=(
    base32
    base64
    basename
    cat
    chmod
    cksum
    comm
    cp
    cut
    date
    dircolors
    dirname
    echo
    env
    expand
    expr
    factor
    false
    fmt
    fold
    hashsum
    head
    install
    join
    link
    ln
    ls
    md5sum
    mkdir
    mktemp
    more
    mv
    nl
    od
    paste
    printenv
    printf
    ptx
    pwd
    readlink
    realpath
    relpath
    rm
    rmdir
    seq
    sha1sum
    sha224sum
    sha256sum
    sha3-224sum
    sha3-256sum
    sha3-384sum
    sha3-512sum
    sha384sum
    sha3sum
    sha512sum
    shake128sum
    shake256sum
    shred
    shuf
    sleep
    sort
    split
    sum
    tac
    tail
    tee
    test
    tr
    true
    truncate
    tsort
    uname
    unexpand
    uniq
    wc
    yes
)

for bin in "${BINS[@]}"
do
  ln -sv uutils "${COOKBOOK_STAGE}/bin/$bin"
done
"""
