cursor = "/ui/left_ptr.png"
bottom_left_corner = "/ui/bottom_left_corner.png"
bottom_right_corner = "/ui/bottom_right_corner.png"
bottom_side = "/ui/vertical.png"
left_side = "/ui/horizontal_left.png"
right_side = "/ui/horizontal_right.png"
window_max = "/ui/window_max.png"
window_max_unfocused = "/ui/window_max_unfocused.png"
window_close = "/ui/window_close.png"
window_close_unfocused = "/ui/window_close_unfocused.png"
