[llvm]
static-libstdcpp = true

[build]
host = ["x86_64-unknown-redox"]
target = ["x86_64-unknown-redox"]
docs = false
submodules = true
verbose = 2

[rust]
thinlto = false
use-jemalloc = false
backtrace = false
rpath = false
codegen-tests = false

[target.x86_64-unknown-redox]
cc = "x86_64-unknown-redox-gcc"
cxx = "x86_64-unknown-redox-g++"
ar = "x86_64-unknown-redox-ar"
linker = "x86_64-unknown-redox-gcc"
llvm-config = "../llvm-config"
crt-static = true
