[packages]
audiod = ""
ca-certificates = ""
contain = ""
coreutils = ""
curl = ""
dash = ""
diffutils = "3.6"
drivers-initfs = ""
drivers = ""
expat = ""
extrautils = ""
findutils = ""
freetype = ""
gdbserver = ""
gnu-make = "4.2.1"
init = ""
installer = ""
ion = ""
ipcd = ""
libiconv = ""
libjpeg = ""
liborbital = ""
libpng = ""
logd = ""
ncurses = "6.1"
netdb = ""
netstack = ""
netsurf = "3.7"
netutils = ""
nghttp2 = ""
nulld = ""
openssl = ""
orbdata = ""
orbital = ""
orbterm = ""
orbutils = ""
pkgutils = ""
ptyd = ""
ramfs = ""
randd = ""
redoxfs = ""
resist = ""
sdl = ""
smith = ""
strace = ""
terminfo = "r2.dc5712b"
userutils = ""
uutils = ""
vim = "8.2"
zerod = ""
zlib = ""
