[source]
tar = "http://zlib.net/zlib-1.2.11.tar.gz"

[build]
template = "custom"
script = """
    export LDFLAGS="--static"
    # See https://stackoverflow.com/questions/21396988/zlib-build-not-configuring-properly-with-cross-compiler-ignores-ar.
    CHOST="${TARGET}" "${COOKBOOK_CONFIGURE}" \
        --prefix="" \
        --static
    "${COOKBOOK_MAKE}" -j "$(nproc)"
    "${COOKBOOK_MAKE}" install DESTDIR="${COOKBOOK_STAGE}"
"""
