[source]
tar = "http://ftp.gnu.org/gnu/bash/bash-4.4.tar.gz"
patches = [
    "redox.patch"
]
script = """
wget -O support/config.sub http://git.savannah.gnu.org/cgit/config.git/plain/config.sub
"""

[build]
template = "custom"
dependencies = [
    "gettext"
]
script = """
COOKBOOK_CONFIGURE_FLAGS+=(
    --disable-readline
    bash_cv_getenv_redef=no
)
cookbook_configure
"""
